//! Project context collection and system prompt assembly for the chat REPL.

use std::fmt::Write;
use std::fs;
use std::path::Path;

use crate::helpers::stringify_error;

use super::{ChatContextFile, ChatProjectContext};

/// Build the system prompt that is prepended to every API request.
pub(crate) fn build_chat_system_prompt(
    custom: Option<&str>,
    project_context: &ChatProjectContext,
    fast_mode: bool,
) -> String {
    let base = concat!(
        "You are Stats Code, an interactive CLI agent for reproducible epidemiology and preventive medicine statistics.\n",
        "Use deterministic local tools whenever the user needs results from local files or wants to run inspect/tableone/rate/model/report workflows.\n",
        "Do not fabricate empirical findings.\n",
        "If the user asks for data-dependent conclusions, call the relevant tool first and base your answer on the tool output.\n",
        "When presenting statistical results:\n",
        "- Always report confidence intervals alongside point estimates (OR, HR, rate).\n",
        "- Use p<0.001 for very small p-values, never report 0.0000.\n",
        "- If the user writes in Chinese, respond in Chinese; respond in English otherwise.\n",
        "- Prefer tools over memory for empirical conclusions.\n",
        "Keep replies concise and operational."
    );
    let mut prompt = String::from(base);
    if fast_mode {
        prompt.push_str(
            "\nFast mode is enabled: prefer shorter answers and avoid tool calls unless they are necessary to answer correctly.",
        );
    }
    let project_section = render_project_context_prompt(project_context);
    if !project_section.is_empty() {
        prompt.push_str("\n\n# Project context\n");
        prompt.push_str(&project_section);
    }
    if let Some(extra) = custom.map(str::trim).filter(|value| !value.is_empty()) {
        prompt.push_str("\n\n# Additional instruction\n");
        prompt.push_str(extra);
    }
    prompt
}

pub(crate) fn format_project_context_summary(project_context: &ChatProjectContext) -> String {
    if project_context.files.is_empty() {
        "cwd only".to_string()
    } else {
        project_context
            .files
            .iter()
            .map(|file| file.label.clone())
            .collect::<Vec<_>>()
            .join(", ")
    }
}

fn render_project_context_prompt(project_context: &ChatProjectContext) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "cwd: {}", project_context.cwd.display());
    if project_context.files.is_empty() {
        let _ = writeln!(
            out,
            "No default context files were detected in the current working directory."
        );
        return out;
    }

    let _ = writeln!(out, "Loaded files:");
    for file in &project_context.files {
        let _ = writeln!(out, "- {}", file.label);
    }
    for file in &project_context.files {
        let _ = writeln!(out, "\n## {}", file.label);
        let _ = writeln!(out, "{}", file.content);
    }
    out
}

pub(crate) fn collect_project_context(cwd: &Path) -> Result<ChatProjectContext, String> {
    const MAX_FILES: usize = 4;
    const MAX_TOTAL_CHARS: usize = 12_000;
    const MAX_FILE_CHARS: usize = 3_500;
    const CANDIDATES: &[&str] = &[
        "STATS.md",       // Generated by /init — highest priority
        "AGENTS.md",
        "analysis.yaml",
        "analysis.yml",
        "README.md",
    ];

    let mut files = Vec::new();
    let mut remaining = MAX_TOTAL_CHARS;
    for relative in CANDIDATES {
        if files.len() >= MAX_FILES || remaining == 0 {
            break;
        }
        let path = cwd.join(relative);
        if !path.is_file() {
            continue;
        }
        let raw = fs::read_to_string(&path).map_err(stringify_error)?;
        let content = truncate_for_prompt(raw.trim(), MAX_FILE_CHARS.min(remaining));
        if content.is_empty() {
            continue;
        }
        remaining = remaining.saturating_sub(content.len());
        files.push(ChatContextFile {
            label: path
                .strip_prefix(cwd)
                .unwrap_or(&path)
                .display()
                .to_string(),
            content,
        });
    }

    Ok(ChatProjectContext {
        cwd: cwd.to_path_buf(),
        files,
    })
}

// A5: Single-pass truncation — avoids O(2n) double char scan
pub(super) fn truncate_for_prompt(content: &str, max_chars: usize) -> String {
    if max_chars == 0 {
        return String::new();
    }
    let mut result = String::with_capacity(max_chars.min(content.len()));
    let mut count = 0usize;
    for ch in content.chars() {
        if count >= max_chars {
            result.push_str("\n... [truncated]");
            return result;
        }
        result.push(ch);
        count += 1;
    }
    result
}
