// scripts/ensure-built.mjs — ensure workspace package dist/ is present and fresh.
//
// Tests import @stats-code/* which resolve to packages/*/dist (package.json
// "main"/"exports"). A clean or stale tree breaks vitest. This module is used by:
//   - CLI: `node scripts/ensure-built.mjs` / `npm run ensure-built`
//   - vitest globalSetup (covers npm test, npm run test:*, npx vitest, IDE)
//
// Rebuild when any package dist entry is missing, or when any watched input is
// newer than the oldest dist marker (source edits without manual rebuild).

import { existsSync, readdirSync, statSync } from 'node:fs';
import { dirname, resolve, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const markers = [
  join(root, 'packages', 'engine', 'dist', 'index.js'),
  join(root, 'packages', 'server', 'dist', 'index.js'),
  join(root, 'packages', 'api', 'dist', 'index.js'),
];

/** Source/config inputs that affect the emitted dist (embed + tsc --build). */
const inputRoots = [
  join(root, 'packages', 'engine', 'src'),
  join(root, 'packages', 'server', 'src'),
  join(root, 'packages', 'api', 'src'),
  join(root, 'packages', 'engine', 'tsconfig.json'),
  join(root, 'packages', 'server', 'tsconfig.json'),
  join(root, 'packages', 'api', 'tsconfig.json'),
  join(root, 'tsconfig.base.json'),
  join(root, 'tsconfig.json'),
  join(root, 'scripts', 'embed-matrix.mjs'),
  join(root, 'scripts', 'embed-templates.mjs'),
];

const INPUT_EXTS = new Set(['.ts', '.tsx', '.js', '.mjs', '.cjs', '.json', '.toml', '.txt']);

/** Generated by embed-* during build; not hand-edited source inputs. */
const GENERATED_BASENAMES = new Set(['matrix-data.ts', 'templates-data.ts']);

function mtimeMs(path) {
  try {
    return statSync(path).mtimeMs;
  } catch {
    return null;
  }
}

function walkMaxMtime(dir, acc = { max: 0 }) {
  let entries;
  try {
    entries = readdirSync(dir, { withFileTypes: true });
  } catch {
    return acc;
  }
  for (const ent of entries) {
    const p = join(dir, ent.name);
    if (ent.isDirectory()) {
      // Skip nested node_modules / dist if ever present under src
      if (ent.name === 'node_modules' || ent.name === 'dist') continue;
      walkMaxMtime(p, acc);
    } else if (
      ent.isFile() &&
      INPUT_EXTS.has(extname(ent.name)) &&
      !GENERATED_BASENAMES.has(ent.name)
    ) {
      const t = mtimeMs(p);
      if (t != null && t > acc.max) acc.max = t;
    }
  }
  return acc;
}

function maxInputMtime() {
  let max = 0;
  for (const p of inputRoots) {
    if (!existsSync(p)) continue;
    const st = statSync(p);
    if (st.isDirectory()) {
      max = Math.max(max, walkMaxMtime(p).max);
    } else {
      max = Math.max(max, st.mtimeMs);
    }
  }
  return max;
}

function minMarkerMtime() {
  let min = Number.POSITIVE_INFINITY;
  for (const p of markers) {
    const t = mtimeMs(p);
    if (t == null) return null;
    if (t < min) min = t;
  }
  return min;
}

/**
 * @returns {{ action: 'skip' | 'build', reason: string }}
 */
export function planEnsureBuilt() {
  const missing = markers.filter((p) => !existsSync(p));
  if (missing.length > 0) {
    return {
      action: 'build',
      reason: `missing dist: ${missing.map((p) => p.slice(root.length + 1)).join(', ')}`,
    };
  }
  const oldestDist = minMarkerMtime();
  const newestInput = maxInputMtime();
  if (oldestDist != null && newestInput > oldestDist) {
    return {
      action: 'build',
      reason: 'source/config newer than package dist',
    };
  }
  return { action: 'skip', reason: 'dist present and up to date' };
}

/**
 * Ensure dist exists and is not older than sources. Returns process exit code.
 * @param {{ silent?: boolean }} [opts]
 */
export function ensureBuilt(opts = {}) {
  const silent = opts.silent === true;
  const plan = planEnsureBuilt();
  if (plan.action === 'skip') {
    if (!silent) {
      // Keep quiet on the happy path so vitest/npm output stays clean.
    }
    return 0;
  }

  console.log(`[ensure-built] ${plan.reason}; running build pipeline…`);
  // Run the same steps as package.json "build", without shell/npm (avoids
  // DEP0190 and keeps Windows/Linux spawn behavior identical).
  const tscJs = join(root, 'node_modules', 'typescript', 'lib', 'tsc.js');
  const steps = [
    [process.execPath, [join(root, 'scripts', 'embed-matrix.mjs')]],
    [process.execPath, [join(root, 'scripts', 'embed-templates.mjs')]],
    [process.execPath, [tscJs, '--build']],
  ];

  for (const [cmd, args] of steps) {
    if (cmd === process.execPath && args[0] === tscJs && !existsSync(tscJs)) {
      console.error('[ensure-built] typescript not installed (node_modules/typescript missing)');
      return 1;
    }
    const result = spawnSync(cmd, args, {
      cwd: root,
      stdio: 'inherit',
      env: process.env,
    });
    if (result.error) {
      console.error(`[ensure-built] failed to spawn ${args[0]}: ${result.error.message}`);
      return 1;
    }
    if (result.status !== 0) {
      return result.status === null ? 1 : result.status;
    }
  }
  return 0;
}

function isMain() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return resolve(entry) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

if (isMain()) {
  process.exit(ensureBuilt());
}
