// scripts/ensure-built.mjs — ensure workspace package dist/ is complete and
// corresponds to the current build inputs.
//
// TypeScript's `--build --noEmit` still updates .tsbuildinfo, so build-info and
// output mtimes cannot prove that emitted JavaScript is current. This guard uses
// a stamp written only after a successful forced emit, plus a full expected
// output check for every source module.

import { createHash } from 'node:crypto';
import {
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  renameSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, resolve, join, extname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const packageNames = ['engine', 'server', 'api'];
const stampPath = join(root, 'build', 'ensure-built.stamp.json');
const STAMP_SCHEMA_VERSION = 1;

/** Source/config inputs that affect the emitted dist (embed + tsc --build). */
const inputRoots = [
  join(root, 'packages', 'engine', 'src'),
  join(root, 'packages', 'server', 'src'),
  join(root, 'packages', 'api', 'src'),
  join(root, 'packages', 'engine', 'tsconfig.json'),
  join(root, 'packages', 'server', 'tsconfig.json'),
  join(root, 'packages', 'api', 'tsconfig.json'),
  join(root, 'tsconfig.base.json'),
  join(root, 'tsconfig.json'),
  join(root, 'package.json'),
  join(root, 'package-lock.json'),
  ...packageNames.map((name) => join(root, 'packages', name, 'package.json')),
  join(root, 'scripts', 'embed-matrix.mjs'),
  join(root, 'scripts', 'embed-templates.mjs'),
  join(root, 'scripts', 'ensure-built.mjs'),
  join(root, 'node_modules', 'typescript', 'package.json'),
];

/** Generated by embed-* during build; not hand-edited source inputs. */
const GENERATED_BASENAMES = new Set(['matrix-data.ts', 'templates-data.ts']);

function collectFiles(path, acc = [], excludeGenerated = false) {
  let stat;
  try {
    stat = statSync(path);
  } catch {
    return acc;
  }
  if (stat.isFile()) {
    if (!excludeGenerated || !GENERATED_BASENAMES.has(path.split(/[\\/]/).at(-1))) {
      acc.push(path);
    }
    return acc;
  }
  if (!stat.isDirectory()) return acc;
  for (const ent of readdirSync(path, { withFileTypes: true })) {
    if (ent.isDirectory() && (ent.name === 'node_modules' || ent.name === 'dist')) continue;
    collectFiles(join(path, ent.name), acc, excludeGenerated);
  }
  return acc;
}

function inputFingerprint() {
  const files = inputRoots.flatMap((path) => collectFiles(path, [], true)).sort();
  const hash = createHash('sha256');
  for (const path of files) {
    hash.update(relative(root, path).replaceAll('\\', '/'));
    hash.update('\0');
    hash.update(readFileSync(path));
    hash.update('\0');
  }
  return hash.digest('hex');
}

function sha256(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

function expectedDistOutputs() {
  const outputs = [];
  for (const name of packageNames) {
    const src = join(root, 'packages', name, 'src');
    const dist = join(root, 'packages', name, 'dist');
    const sources = collectFiles(src).filter((path) => {
      const extension = extname(path);
      return (extension === '.ts' || extension === '.tsx') && !path.endsWith('.d.ts');
    });
    for (const source of sources) {
      const base = join(dist, relative(src, source).replace(/\.tsx?$/, ''));
      outputs.push(`${base}.js`, `${base}.js.map`, `${base}.d.ts`, `${base}.d.ts.map`);
    }
  }
  return outputs.sort();
}

export function findMissingDistOutputs() {
  return expectedDistOutputs().filter((path) => !existsSync(path));
}

function outputManifest() {
  return expectedDistOutputs().map((path) => {
    const bytes = readFileSync(path);
    return {
      path: relative(root, path).replaceAll('\\', '/'),
      bytes: bytes.byteLength,
      sha256: sha256(bytes),
    };
  });
}

function validateOutputManifest(stampedOutputs) {
  if (!Array.isArray(stampedOutputs)) return false;
  const expected = expectedDistOutputs().map((path) => relative(root, path).replaceAll('\\', '/'));
  if (stampedOutputs.length !== expected.length) return false;
  for (let index = 0; index < expected.length; index += 1) {
    const record = stampedOutputs[index];
    if (
      record?.path !== expected[index] ||
      typeof record.bytes !== 'number' ||
      typeof record.sha256 !== 'string'
    ) {
      return false;
    }
    const absolute = join(root, ...record.path.split('/'));
    if (!existsSync(absolute)) return false;
    const bytes = readFileSync(absolute);
    if (bytes.byteLength !== record.bytes || sha256(bytes) !== record.sha256) return false;
  }
  return true;
}

function readStamp() {
  try {
    const parsed = JSON.parse(readFileSync(stampPath, 'utf8'));
    if (
      parsed?.schemaVersion === STAMP_SCHEMA_VERSION &&
      typeof parsed.inputSha256 === 'string' &&
      Array.isArray(parsed.outputs)
    ) {
      return parsed;
    }
  } catch {
    // Missing or malformed stamp means a rebuild is required.
  }
  return null;
}

function writeStamp(inputSha256, outputs) {
  mkdirSync(dirname(stampPath), { recursive: true });
  const temporary = `${stampPath}.${process.pid}.tmp`;
  writeFileSync(temporary, `${JSON.stringify({
    schemaVersion: STAMP_SCHEMA_VERSION,
    inputSha256,
    outputs,
  }, null, 2)}\n`);
  renameSync(temporary, stampPath);
}

/**
 * @returns {{ action: 'skip' | 'build', reason: string }}
 */
export function planEnsureBuilt() {
  const missing = findMissingDistOutputs();
  if (missing.length > 0) {
    return {
      action: 'build',
      reason: `missing dist output: ${missing
        .slice(0, 3)
        .map((path) => relative(root, path))
        .join(', ')}${missing.length > 3 ? ` (+${missing.length - 3} more)` : ''}`,
    };
  }
  const stamp = readStamp();
  if (!stamp) {
    return { action: 'build', reason: 'missing or invalid successful-emit stamp' };
  }
  if (stamp.inputSha256 !== inputFingerprint()) {
    return {
      action: 'build',
      reason: 'build inputs differ from successful-emit stamp',
    };
  }
  if (!validateOutputManifest(stamp.outputs)) {
    return {
      action: 'build',
      reason: 'dist content differs from successful-emit stamp',
    };
  }
  return { action: 'skip', reason: 'dist content matched to build inputs and stamp' };
}

/**
 * Ensure dist exists and matches current build inputs. Returns process exit code.
 * @param {{ silent?: boolean, force?: boolean }} [opts]
 */
export function ensureBuilt(opts = {}) {
  const silent = opts.silent === true;
  const plan = opts.force === true
    ? { action: 'build', reason: 'forced build requested' }
    : planEnsureBuilt();
  if (plan.action === 'skip') {
    if (!silent) {
      // Keep quiet on the happy path so vitest/npm output stays clean.
    }
    return 0;
  }

  console.log(`[ensure-built] ${plan.reason}; running build pipeline…`);
  const inputBeforeBuild = inputFingerprint();
  // Run the same steps as package.json "build", without shell/npm (avoids
  // DEP0190 and keeps Windows/Linux spawn behavior identical).
  const tscJs = join(root, 'node_modules', 'typescript', 'lib', 'tsc.js');
  const steps = [
    [process.execPath, [join(root, 'scripts', 'embed-matrix.mjs')]],
    [process.execPath, [join(root, 'scripts', 'embed-templates.mjs')]],
    [process.execPath, [tscJs, '--build', '--force']],
  ];

  for (const [cmd, args] of steps) {
    if (cmd === process.execPath && args[0] === tscJs && !existsSync(tscJs)) {
      console.error('[ensure-built] typescript not installed (node_modules/typescript missing)');
      return 1;
    }
    const result = spawnSync(cmd, args, {
      cwd: root,
      stdio: 'inherit',
      env: process.env,
    });
    if (result.error) {
      console.error(`[ensure-built] failed to spawn ${args[0]}: ${result.error.message}`);
      return 1;
    }
    if (result.status !== 0) {
      return result.status === null ? 1 : result.status;
    }
  }
  const missing = findMissingDistOutputs();
  if (missing.length > 0) {
    console.error(`[ensure-built] build completed but ${missing.length} expected output(s) are missing`);
    return 1;
  }
  try {
    const inputAfterBuild = inputFingerprint();
    if (inputAfterBuild !== inputBeforeBuild) {
      console.error('[ensure-built] build inputs changed while the build was running');
      return 1;
    }
    writeStamp(inputAfterBuild, outputManifest());
  } catch (error) {
    console.error(`[ensure-built] failed to write successful-emit stamp: ${error.message}`);
    return 1;
  }
  return 0;
}

function isMain() {
  const entry = process.argv[1];
  if (!entry) return false;
  try {
    return resolve(entry) === fileURLToPath(import.meta.url);
  } catch {
    return false;
  }
}

if (isMain()) {
  process.exit(ensureBuilt({ force: process.argv.includes('--force') }));
}
