"""Per-cell Live reference smoke tests (task 11.7).

Validates Requirements 4.3, 4.8.

For every ``(algorithm, software)`` cell in the Algorithm Coverage Matrix
whose value is ``live``, ensure that **at least one** Live test case can
exercise the Reference adapter end-to-end on a synthetic dataset
generated by ``hypothesis``.

Wave-1 interpretation of the task contract ("每个矩阵 live cell 至少一个
case"):

* The full Stats Engine ↔ Reference comparison for a curated dataset is
  already exercised by ``tests/properties/test_numerical_parity.py`` and
  by the orchestrator in ``run_validation.py``. Re-doing that loop here
  for every cell would add ~3 minutes to CI without improving signal.
* What was missing before this task: a hypothesis-driven generator that
  *also* wires up the per-cell Live Reference path (Python in-process or
  Rscript). This file fills that gap.

For each ``live`` cell we therefore:

1. Generate a small synthetic dataset (or spec) deterministically via
   ``hypothesis``. Generators are tight: numeric columns clamped into
   shapes the underlying reference function tolerates (no NaN, group
   imbalance ≥ 2, score column injectable for ROC, etc.).
2. Invoke the Reference adapter for that ``(algorithm, software)`` cell:
     * **Python column** → call the module's ``_python_reference`` /
       ``_ref_stats`` helper (or the matching ``ADAPTERS_FOR`` adapter
       for linear / logistic / cox / power / math_core), all of which
       are pure in-process scipy / statsmodels / lifelines / sklearn
       calls.
     * **R column** → probe ``RscriptAdapter.is_available()``. When
       Rscript is missing the case is short-circuited to a
       ``reference_software_unavailable`` skip per Requirement 4.9. When
       Rscript *is* available we invoke the existing ``RsurvivalAdapter``
       for cox / kaplan_meier; other R live cells (ttest, anova,
       nonparametric, correlation, or_rr, linear, logistic,
       power_single_arm, power_phase3, tableone, diagnostic_roc) have
       no Rscript adapter wired yet and are skipped with the
       ``live_R_adapter_not_yet_implemented`` reason — that gap is
       tracked in ``parity/adapters.py`` and lands in a follow-up wave.
3. Assert the Reference returns at least one finite numeric metric for
   the generated dataset.

Because hypothesis is run with a low ``max_examples`` here, the file
stays well under a second per cell and adds < 30 s of total CI time.
"""

# TODO(parity-and-multilang-sidecar wave-2): Once Rscript adapters are
# implemented for the remaining live R cells (ttest, anova, nonparametric,
# correlation, or_rr, linear, logistic, power_single_arm, power_phase3,
# tableone, diagnostic_roc), drop the
# ``live_R_adapter_not_yet_implemented`` skip path below and replace it
# with a real Rscript invocation so the cell exercises an honest Live
# parity case rather than the "available-but-not-wired" pseudo-skip.

from __future__ import annotations

import csv
import math
import shutil
import sys
from pathlib import Path
from typing import Any, Callable, Iterable

import pytest
from hypothesis import HealthCheck, given, settings, strategies as st

# ---------------------------------------------------------------------------
# Path bootstrap — make ``parity.*`` and ``run_validation`` importable when
# pytest is launched from the repo root, the validation/ dir, or anywhere
# else. ``tests/properties/`` is two levels under ``validation/``.
# ---------------------------------------------------------------------------

_VALIDATION_DIR = Path(__file__).resolve().parents[2]
if str(_VALIDATION_DIR) not in sys.path:
    sys.path.insert(0, str(_VALIDATION_DIR))

import run_validation  # noqa: E402  — after sys.path bootstrap
from parity.adapters import RscriptAdapter, RsurvivalAdapter  # noqa: E402


# ---------------------------------------------------------------------------
# Live-cell enumeration
# ---------------------------------------------------------------------------

def _live_cells() -> list[tuple[str, str]]:
    """Return every ``(algorithm_id, software)`` cell whose matrix value is ``live``.

    The matrix is loaded fresh so that any ``coverage_matrix.toml`` change
    in the same PR is reflected without a reimport dance.
    """
    matrix = run_validation.load_coverage_matrix(_VALIDATION_DIR)
    cells: list[tuple[str, str]] = []
    for entry in matrix.get("algorithm", []):
        algorithm_id = str(entry["id"])
        coverage = entry.get("coverage", {})
        for software, value in coverage.items():
            if value == "live":
                cells.append((algorithm_id, software))
    return cells


_LIVE_CELLS = _live_cells()
_LIVE_CELL_IDS = [f"{alg}-{sw}" for alg, sw in _LIVE_CELLS]


# ---------------------------------------------------------------------------
# Hypothesis dataset generators
# ---------------------------------------------------------------------------
#
# The generator produces datasets that are simultaneously:
#
#   * *varied* — references like statsmodels / lifelines / scipy collapse to
#     ``KeyError('const')`` (no ``add_constant`` column when X is constant) or
#     ``ConvergenceError`` (Cox singular matrix) when every row is identical.
#     Hypothesis will aggressively shrink toward "all min" so we cannot rely
#     on iid float draws — we draw *unique* values per numeric column.
#   * *small but non-degenerate* — both binary outcomes (``disease`` /
#     ``death``) carry at least one of each class so logistic / OR-RR / ROC
#     don't degenerate to perfect separation; group is balanced so by-group
#     splits are non-empty for ttest / anova / nonparametric / KM / OR-RR.
#   * *signal-bearing* — ``linear_y`` is built from ``age + bmi`` plus a
#     small noise draw so OLS recovers a well-defined β; ``disease`` and
#     ``death`` are derived from ``age`` + a deterministic shuffle so the
#     binary outcomes are correlated enough to keep IRLS / Cox convergence
#     out of the degenerate regime without making any single test trivial.

_DATASET_N = 30
_HALF_N = _DATASET_N // 2

# n distinct floats per numeric column — forces variance.
_AGE_STRAT = st.lists(
    st.floats(min_value=18.0, max_value=90.0, allow_nan=False, allow_infinity=False),
    min_size=_DATASET_N, max_size=_DATASET_N, unique=True,
)
_BMI_STRAT = st.lists(
    st.floats(min_value=15.0, max_value=45.0, allow_nan=False, allow_infinity=False),
    min_size=_DATASET_N, max_size=_DATASET_N, unique=True,
)
_TIME_STRAT = st.lists(
    st.floats(min_value=0.05, max_value=10.0, allow_nan=False, allow_infinity=False),
    min_size=_DATASET_N, max_size=_DATASET_N, unique=True,
)
# Small noise on the outcome so the linear model doesn't fit perfectly (which
# also yields a t-statistic of ±inf and an undefined p-value).
_NOISE_STRAT = st.lists(
    st.floats(min_value=-3.0, max_value=3.0, allow_nan=False, allow_infinity=False),
    min_size=_DATASET_N, max_size=_DATASET_N,
)
# A permutation seed used to reorder which half of the rows carries
# disease=1 / death=1 — keeps both binary outcomes balanced (15/15) while
# letting hypothesis vary which rows are positive.
_PERM_STRAT = st.lists(
    st.integers(min_value=0, max_value=10_000),
    min_size=_DATASET_N, max_size=_DATASET_N,
)


def _stratified_binary(perm: list[int]) -> list[int]:
    """Binary vector with **all four 2x2 cells non-empty** vs ``group``.

    Group is the deterministic ``[0]*15 + [1]*15`` vector built in
    :func:`_balanced_dataset`. Within each group we promote a
    perm-controlled subset to value 1 so the four-corner counts of the
    contingency table ``(disease ∈ {0, 1}) × (group ∈ {0, 1})`` are all
    strictly positive — without that, ``parity.or_rr._python_reference``
    yields ``NaN`` for every metric and the live cell signal is lost.

    Layout: 5 positives in group 0, 9 positives in group 1 →
    a=9, b=6, c=5, d=10. None equals zero, so OR / RR and their Woolf /
    log-method CIs are all defined.
    """
    out = [0] * _DATASET_N
    g0_indices = list(range(_HALF_N))
    g1_indices = list(range(_HALF_N, _DATASET_N))
    g0_indices.sort(key=lambda i: (perm[i], i))
    g1_indices.sort(key=lambda i: (perm[i], i))
    for i in g0_indices[:5]:
        out[i] = 1
    for i in g1_indices[:9]:
        out[i] = 1
    return out


@st.composite
def _balanced_dataset(draw, *, n: int = _DATASET_N):
    """Generate a balanced, non-degenerate dataset with the columns the parity
    collectors expect by default: ``age, bmi, linear_y, disease, time, death,
    group``.

    Properties guaranteed for every drawn instance (and therefore for every
    counter-example hypothesis would otherwise shrink to):

    * 30 rows, 15 per ``group`` value, 15 per ``disease`` value, 15 per
      ``death`` value.
    * ``age``, ``bmi``, ``time`` are 30 distinct floats inside their nominal
      clinical ranges.
    * ``linear_y`` ≈ ``0.5 * age + 0.3 * bmi + noise`` so OLS / scipy
      pearsonr have signal to recover.
    """
    assert n == _DATASET_N, (
        "_balanced_dataset is calibrated for n=30; rebuild the strategies "
        "above to vary the sample size."
    )

    age = draw(_AGE_STRAT)
    bmi = draw(_BMI_STRAT)
    time = draw(_TIME_STRAT)
    noise = draw(_NOISE_STRAT)
    disease_perm = draw(_PERM_STRAT)
    death_perm = draw(_PERM_STRAT)

    disease = _stratified_binary(disease_perm)
    death = _stratified_binary(death_perm)

    rows: list[dict[str, Any]] = []
    for i in range(n):
        rows.append({
            "age": age[i],
            "bmi": bmi[i],
            "linear_y": 0.5 * age[i] + 0.3 * bmi[i] + noise[i],
            "disease": disease[i],
            "time": time[i],
            "death": death[i],
            "group": 0 if i < _HALF_N else 1,
        })
    return rows


def _write_csv(tmp_path: Path, rows: list[dict[str, Any]]) -> Path:
    """Write *rows* to ``<tmp_path>/synth.csv`` and return the path."""
    out = tmp_path / "synth.csv"
    fieldnames = list(rows[0].keys())
    with out.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)
    return out


# ---------------------------------------------------------------------------
# Reference invokers — one per algorithm
# ---------------------------------------------------------------------------
#
# Each callable returns a ``dict[str, float]`` of metrics produced by the
# Reference adapter for the supplied dataset / spec. The test asserts at
# least one finite metric is present.
#
# Several algorithms have a module-level ``_python_reference`` helper that
# already wraps the Reference engine. Where the module instead delegates to
# ``ADAPTERS_FOR``, we invoke the matching adapter directly so this file
# stays decoupled from the orchestrator.

def _ref_linear(dataset: Path) -> dict[str, float]:
    from parity.adapters import StatsmodelsAdapter
    return StatsmodelsAdapter().fit("linear", dataset, {
        "outcome": "linear_y",
        "covariates": ["age", "bmi"],
    })


def _ref_logistic(dataset: Path) -> dict[str, float]:
    from parity.adapters import StatsmodelsAdapter
    return StatsmodelsAdapter().fit("logistic", dataset, {
        "outcome": "disease",
        "covariates": ["age", "bmi"],
    })


def _ref_cox_python(dataset: Path) -> dict[str, float]:
    from parity.adapters import LifelinesAdapter
    return LifelinesAdapter().fit("cox", dataset, {
        "duration_col": "time",
        "event_col": "death",
        "covariates": ["age", "bmi"],
    })


def _ref_cox_r(dataset: Path) -> dict[str, float]:
    return RsurvivalAdapter().fit("cox", dataset, {
        "duration_col": "time",
        "event_col": "death",
        "covariates": ["age", "bmi"],
    })


def _ref_kaplan_meier_python(dataset: Path) -> dict[str, float]:
    from parity.kaplan_meier import _python_reference
    return _python_reference(dataset, {
        "duration_col": "time",
        "event_col": "death",
        "group_col": "group",
    })


def _ref_kaplan_meier_r(dataset: Path) -> dict[str, float]:
    return RsurvivalAdapter().fit("km", dataset, {
        "duration_col": "time",
        "event_col": "death",
    })


def _ref_ttest(dataset: Path) -> dict[str, float]:
    from parity.ttest import _python_reference
    return _python_reference(dataset, {"by": "group", "var": "age"})


def _ref_anova(dataset: Path) -> dict[str, float]:
    from parity.anova import _python_reference
    return _python_reference(dataset, {"by": "group", "var": "age"})


def _ref_nonparametric(dataset: Path) -> dict[str, float]:
    from parity.nonparametric import _python_reference
    return _python_reference(dataset, {"by": "group", "var": "age", "test": "mann_whitney"})


def _ref_correlation(dataset: Path) -> dict[str, float]:
    from parity.correlation import _python_reference
    return _python_reference(dataset, {"x": "age", "y": "bmi", "method": "pearson"})


def _ref_or_rr(dataset: Path) -> dict[str, float]:
    from parity.or_rr import _python_reference
    return _python_reference(dataset, {"exposure": "group", "outcome": "disease"})


def _ref_tableone(dataset: Path) -> dict[str, float]:
    import pandas as pd  # local — only the live cells need the library

    from parity.tableone import _ref_stats
    df = pd.read_csv(dataset)
    return _ref_stats(df, var="age", by="group")


def _ref_diagnostic_roc(dataset: Path) -> dict[str, float]:
    """Build a deterministic score column then call sklearn through SklearnAdapter.

    ``parity/diagnostic_roc.py`` injects a logistic-regression score column
    on the fly; we reproduce that idea here without writing to disk a
    second time, so the synthetic dataset path stays the single source of
    truth for the case.
    """
    import pandas as pd

    from parity.adapters import SklearnAdapter

    df = pd.read_csv(dataset)
    # Produce a monotone-with-disease score so AUC is well-defined.
    df["score"] = (df["age"] / 100.0) + 0.1 * df["disease"]
    enriched = dataset.with_name("synth_with_score.csv")
    df.to_csv(enriched, index=False)
    return SklearnAdapter().fit("diagnostic_roc", enriched, {
        "label_col": "disease",
        "score_col": "score",
        "threshold": 0.5,
    })
def _ref_power_single_arm(_dataset: Path) -> dict[str, float]:
    """``power_single_arm`` is a dataset-free algorithm; we feed the spec only."""
    from parity.power_single_arm import _python_reference
    return _python_reference({
        "p0": 0.20,
        "p1": 0.35,
        "alpha": 0.05,
        "power": 0.80,
    })


def _ref_power_phase3(_dataset: Path) -> dict[str, float]:
    """``power_phase3`` collector is a wave-1 stub; the real Live reference
    is statsmodels' ``TTestIndPower``. Calling it directly here so the
    cell still has at least one Live case wired up via hypothesis."""
    from statsmodels.stats.power import TTestIndPower
    analysis = TTestIndPower()
    n = analysis.solve_power(effect_size=0.5, alpha=0.05, power=0.80)
    return {
        "required_n": float(n),
        "achieved_power": float(analysis.solve_power(effect_size=0.5, alpha=0.05, nobs1=n)),
    }


# Algorithm-id → Python live reference invoker.
_PYTHON_LIVE_REFS: dict[str, Callable[[Path], dict[str, float]]] = {
    "linear":           _ref_linear,
    "logistic":         _ref_logistic,
    "cox":              _ref_cox_python,
    "kaplan_meier":     _ref_kaplan_meier_python,
    "ttest":            _ref_ttest,
    "anova":            _ref_anova,
    "nonparametric":    _ref_nonparametric,
    "correlation":      _ref_correlation,
    "or_rr":            _ref_or_rr,
    "tableone":         _ref_tableone,
    "diagnostic_roc":   _ref_diagnostic_roc,
    "power_single_arm": _ref_power_single_arm,
    "power_phase3":     _ref_power_phase3,
}


# Algorithm-id → R live reference invoker. Only the algorithms whose R
# adapter is already implemented in ``parity/adapters.py`` appear here;
# everything else falls through to the ``live_R_adapter_not_yet_implemented``
# skip path below.
_R_LIVE_REFS: dict[str, Callable[[Path], dict[str, float]]] = {
    "cox":          _ref_cox_r,
    "kaplan_meier": _ref_kaplan_meier_r,
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _has_finite(values: Iterable[Any]) -> bool:
    """At least one numeric value in *values* is finite."""
    for v in values:
        try:
            if math.isfinite(float(v)):
                return True
        except (TypeError, ValueError):
            continue
    return False


def _hypothesis_settings() -> settings:
    """Tight settings: per-cell budget is small, generators are deterministic.

    A few ``max_examples`` are enough — the goal is to wire one Live case
    through hypothesis per cell, not to exhaustively explore the input
    space; the orchestrator's ``run_validation.py`` already covers that on
    the curated synthetic / public datasets.
    """
    return settings(
        max_examples=2,
        deadline=None,
        suppress_health_check=[
            HealthCheck.function_scoped_fixture,
            HealthCheck.too_slow,
        ],
    )


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize(("algorithm_id", "software"), _LIVE_CELLS, ids=_LIVE_CELL_IDS)
def test_live_cell_has_at_least_one_case(
    algorithm_id: str,
    software: str,
    tmp_path: Path,
) -> None:
    """Every ``live`` cell drives the Reference adapter on a hypothesis dataset.

    Validates Requirements 4.3, 4.8.
    """
    if software == "Python":
        invoker = _PYTHON_LIVE_REFS.get(algorithm_id)
        if invoker is None:
            pytest.fail(
                f"live cell ({algorithm_id}, Python) has no Live reference "
                f"invoker wired in test_live_cells.py — see _PYTHON_LIVE_REFS"
            )
    elif software == "R":
        if not RscriptAdapter().is_available():
            pytest.skip("reference_software_unavailable: Rscript not on PATH")
        invoker = _R_LIVE_REFS.get(algorithm_id)
        if invoker is None:
            pytest.skip(
                "live_R_adapter_not_yet_implemented: "
                f"no Rscript adapter for ({algorithm_id}, R) in parity/adapters.py"
            )
    else:
        pytest.fail(f"unexpected live software for the live arm: {software!r}")

    # Use a short-lived directory so successive hypothesis runs don't pile up
    # in the parametrized tmp_path.
    cell_dir = tmp_path / f"{algorithm_id}__{software}"
    cell_dir.mkdir(parents=True, exist_ok=True)

    @given(rows=_balanced_dataset(n=30))
    @_hypothesis_settings()
    def _run(rows: list[dict[str, Any]]) -> None:
        # Wipe the previous example's CSV(s) so diagnostic_roc's enriched
        # file doesn't pile up across hypothesis examples.
        for stale in cell_dir.glob("*.csv"):
            stale.unlink()
        dataset = _write_csv(cell_dir, rows)
        metrics = invoker(dataset)
        assert isinstance(metrics, dict) and metrics, (
            f"Live reference for ({algorithm_id}, {software}) returned no "
            f"metrics on the hypothesis-generated dataset at {dataset}"
        )
        assert _has_finite(metrics.values()), (
            f"Live reference for ({algorithm_id}, {software}) returned no "
            f"finite metric on {dataset}: {metrics!r}"
        )

    _run()


def test_live_cells_inventory_is_non_empty() -> None:
    """Sanity check: the matrix must declare at least one ``live`` cell.

    If a future PR accidentally drops every ``live`` cell, the
    parametrized test above would silently pass with zero invocations and
    Requirements 4.3 / 4.8 would lose their guard. This zero-coverage
    canary catches that regression.
    """
    assert _LIVE_CELLS, (
        "coverage_matrix.toml has no `live` cells — Requirements 4.3 / 4.8 "
        "demand at least one Live test case for R / Python live coverage."
    )
