// tests/property/workflow-yaml.property.test.ts — Properties 13 & 14 (tasks 13.16, 13.17).
//
// Property 13 (YAML byte round-trip): for ALL valid documents (including ones
// carrying comments, blank lines, and inline trivia), parsing then re-emitting
// with the retained document handle reproduces the exact input bytes
// (Requirements 12.1, 12.2).
//
// Property 14 (YAML model round-trip): for ALL valid models, the canonical
// pretty-print (no doc handle) re-parses to an equal model and the canonical
// form is a fixpoint (Requirements 12.3, 12.4).
//
// Validates: Requirements 12.1, 12.2, 12.3, 12.4

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { snapshot } from '@stats-code/engine';

const { workflowYaml } = snapshot;
const { parse, prettyPrint } = workflowYaml;

const SHA = '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
const SHA2 = 'fedcba9876543210fedcba9876543210fedcba9876543210fedcba9876543210';

const safeName = fc.stringMatching(/^[A-Za-z][A-Za-z0-9_-]{0,10}$/);
const shaArb = fc.constantFrom(SHA, SHA2);

// --- Property 13: byte round-trip over documents with arbitrary trivia -------

// Build a textual document, optionally decorated with comments/blank lines, so
// the doc-side handle must preserve those bytes verbatim.
const triviaDocArb = fc
  .record({
    topComment: fc.option(fc.constantFrom('# generated by stats-code', '# audit workflow'), {
      nil: undefined,
    }),
    blankAfterVersion: fc.boolean(),
    inlineComment: fc.option(fc.constantFrom('   # inline', ' #x'), { nil: undefined }),
    path: safeName.map((s) => `${s}.csv`),
    sha: shaArb,
  })
  .map(({ topComment, blankAfterVersion, inlineComment, path, sha }) => {
    let text = '';
    if (topComment) text += `${topComment}\n`;
    text += 'schema_version: 1\n';
    if (blankAfterVersion) text += '\n';
    text += 'input_dataset:\n';
    text += `  path: ${path}${inlineComment ?? ''}\n`;
    text += `  sha256: ${sha}\n`;
    text += 'steps: []\n';
    return text;
  });

describe('Property 13: YAML byte round-trip (Requirements 12.1, 12.2)', () => {
  it('prettyPrint(_, doc) reproduces the exact input bytes for arbitrary trivia', () => {
    fc.assert(
      fc.property(triviaDocArb, (text) => {
        const { workflow, doc } = parse(text);
        expect(prettyPrint(workflow, doc)).toBe(text);
      }),
      { numRuns: 300 },
    );
  });
});

// --- Property 14: model round-trip + canonical fixpoint ----------------------

const artifactArb = fc.record({ path: safeName.map((s) => `${s}.csv`), sha256: shaArb });
const stepArb = fc.record({
  id: safeName,
  algorithm: fc.constantFrom('tableone', 'ttest', 'cox', 'logistic', 'linear'),
  params: fc.constantFrom({}, { by: 'arm' }, { vars: ['a', 'b'] }, { n: 5 }, { nested: { k: 1 } }),
  inputs: fc.array(artifactArb, { maxLength: 2 }),
  outputs: fc.array(artifactArb, { maxLength: 2 }),
  startedAtUtc: fc.constant('2025-01-01T00:00:00Z'),
  endedAtUtc: fc.constant('2025-01-01T00:00:01Z'),
});

const workflowArb = fc
  .record({
    schemaVersion: fc.constant(1 as const),
    inputDataset: artifactArb,
    steps: fc.array(stepArb, { maxLength: 4 }),
  })
  .map((w) => ({
    ...w,
    steps: w.steps.filter((s, i, arr) => arr.findIndex((o) => o.id === s.id) === i),
  }));

describe('Property 14: YAML model round-trip + fixpoint (Requirements 12.3, 12.4)', () => {
  it('canonical pretty-print re-parses to an equal model and is a fixpoint', () => {
    fc.assert(
      fc.property(workflowArb, (w) => {
        const canon1 = prettyPrint(w as workflowYaml.Workflow);
        const reparsed = parse(canon1).workflow;
        const canon2 = prettyPrint(reparsed);
        // Fixpoint: re-serializing the reparsed model yields identical bytes.
        expect(canon2).toBe(canon1);
        // Structural equality of the round-tripped model.
        expect(reparsed.schemaVersion).toBe(1);
        expect(reparsed.steps.length).toBe(w.steps.length);
        for (let i = 0; i < w.steps.length; i += 1) {
          expect(reparsed.steps[i]!.id).toBe(w.steps[i]!.id);
          expect(reparsed.steps[i]!.algorithm).toBe(w.steps[i]!.algorithm);
        }
      }),
      { numRuns: 200 },
    );
  });
});
